temporalio_common.settings:
  type: config_object
  label: 'Temporal.io common settings'
  mapping:
    temporal_ui_base_url: { type: string, label: 'Temporal.io base URL' }
    hmac_secret:      { type: string, label: 'HMAC secret' }
